version: '3.8'

services:
  astrowind:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: astrowind
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.astrowind.rule=Host(`your-domain.com`)'
      - 'traefik.http.routers.astrowind.entrypoints=websecure'
      - 'traefik.http.routers.astrowind.tls.certresolver=letsencrypt'
      - 'traefik.http.services.astrowind.loadbalancer.server.port=3000'
      - 'traefik.docker.network=traefik'
      - 'coolify.managed=true'
      - 'coolify.type=application'
      - 'coolify.healthcheck.path=/health'
      - 'coolify.healthcheck.port=3000'
    healthcheck:
      test: ['CMD', 'wget', '--quiet', '--tries=1', '--spider', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  traefik:
    external: true
