# Minimal Nixpacks configuration for Astro
# Let Nixpacks auto-detect Node.js and npm

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx serve dist -p 3000"
